title: Leo Hunt # your name (or website title) here
logo: "images/IMG_2378.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven analyst with an expertise in mining social media data for actionable insights 
  I want some pizza  <br><br>
  <a href="https://www.linkedin.com/in/leonardmhuntjr/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
